from pathlib import Path

import pytest
from testing_utils import BazelTools

FAILED_CONFIGS = []


# Cmdline options
def pytest_addoption(parser):
    parser.addoption(
        "--traces",
        choices=["none", "target", "all"],
        default="none",
        help="Verbosity of traces in output and HTML report. "
        '"none" - show no traces, '
        '"target" - show traces generated by test code, '
        '"all" - show all traces. ',
    )

    parser.addoption(
        "--rust-target-name",
        type=str,
        default="//feature_integration_tests/rust_test_scenarios:rust_test_scenarios",
        help="Rust test scenario executable target.",
    )
    parser.addoption(
        "--rust-target-path",
        type=Path,
        help="Rust test scenario executable target.",
    )
    parser.addoption(
        "--build-scenarios",
        action="store_true",
        help="Build test scenarios executables.",
    )
    parser.addoption(
        "--build-scenarios-timeout",
        type=float,
        default=180.0,
        help="Build command timeout in seconds. Default: %(default)s",
    )
    parser.addoption(
        "--default-execution-timeout",
        type=float,
        default=5.0,
        help="Default execution timeout in seconds. Default: %(default)s",
    )


# Hooks
@pytest.hookimpl(tryfirst=True)
def pytest_sessionstart(session):
    try:
        # Build scenarios.
        if session.config.getoption("--build-scenarios"):
            build_timeout = session.config.getoption("--build-scenarios-timeout")

            # Build Rust test scenarios.
            print("Building Rust test scenarios executable...")
            cargo_tools = BazelTools(option_prefix="rust", build_timeout=build_timeout)
            rust_target_name = session.config.getoption("--rust-target-name")
            cargo_tools.build(rust_target_name)

    except Exception as e:
        pytest.exit(str(e), returncode=1)
