# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
exports_files(
    [
        "qemu_target_config.json",
    ],
)

exports_files([
    "etc/logging.json",
    "etc/mw_com_config.json",
])

filegroup(
    name = "etc_configs",
    srcs = [
        "etc/logging.json",
        "etc/mw_com_config.json",        
    ],
    visibility = ["//visibility:public"],
)
