# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************


exports_files([
    "startup.sh",
    "network_setup.sh",
    "network_setup_dhcp.sh",
    "dhcpcd.conf",
    "pci_server.cfg",
    "pci_hw.cfg",
    "qcrypto.conf",
    "passwd",
    "group",
    "sshd_config",
    "ssh_host_rsa_key",
    "ssh_host_rsa_key.pub",
    "hostname",
    "profile",
    "network_capture.sh"
])
